server:
  applicationConnectors:
    - type: http
      port: 8090
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8091
      bindHost: 0.0.0.0

swagger:
  resourcePackage: cloudApiHttp.resources


  #logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
#  level: INFO